export enum SynonymActionTypes {
    GET_SYNONYMS_STARTED = 'GET_SYNONYMS_STARTED',
    GET_SYNONYMS_SUCCESS = 'GET_SYNONYMS_SUCCESS',
    GET_SYNONYMS_FAILED = 'GET_SYNONYMS_FAILED',

    POST_SYNONYM_STARTED = 'POST_SYNONYM_STARTED',
    POST_SYNONYM_SUCCESS = 'POST_SYNONYM_SUCCESS',
    POST_SYNONYM_FAILED = 'POST_SYNONYM_FAILED',
}